// Mocks generated by Mockito 5.0.16 from annotations
// in blog_app/test/layers/data/datasources/routines_local_data_soucre_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as i1;
import 'package:blog_app/core/db/db_helper.dart' as i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends i1.Mock implements i2.DatabaseHelper {
  MockDatabaseHelper() {
    i1.throwOnMissingStub(this);
  }
}
